language: python
python:
  - "3.6"
sudo: false

os: 
  - linux
dist: xenial
compiler: 
  - gcc

# install dependencies

addons:
  apt:
    update: true
    packages:
      - libhdf5-serial-dev
      - zlib1g-dev
      - libatlas-base-dev
      - lcov
      - swig3.0
install:
  - pyenv shell 2.7 3.6
  - mkdir -p ~/bin/ && ln -s /usr/bin/swig3.0 ~/bin/swig && export PATH=~/bin/:$PATH
  - pip3 install --upgrade setuptools wheel pkgconfig numpy
  - pip3 install -r ./travis_requirements.txt
  - pip3 install .

# run tests

script:  
  - python3 -m pytest ./test/test_objective.py

after_success:
  - python3 ./test/coverage.py
  - bash <(curl -s https://codecov.io/bash) -f coverage_py.xml -X fix

cache: pip
