language: generic
sudo: false

branches:
  only:
    - master

os: linux
dist: xenial
compiler: gcc
addons:
  apt:
    update: true
    packages:
      - libhdf5-serial-dev
      - zlib1g-dev
      - libatlas-base-dev
      - lcov
      - swig3.0
after_success: 
  - python3 ./test/testCoverage.py
  - bash <(curl -s https://codecov.io/bash) -f coverage_py.xml -X fix -cF python

install:
  - pyenv shell 2.7 3.6
  - mkdir -p ~/bin/ && ln -s /usr/bin/swig3.0 ~/bin/swig && export PATH=~/bin/:$PATH; fi
  - pip3 install --user --upgrade setuptools wheel pkgconfig numpy
  - pip3 install --user coverage scipy dlib amici
  - python3 setup.py install
    
script:  
  - python3 ./test/test_sbml_conversion.py
