language: python
python:
  - "3.6"

os:
  - linux
dist:
  - xenial
compiler:
  - gcc

# install dependencies

addons:
  apt:
    update: true
    packages:
      - libhdf5-serial-dev
      - zlib1g-dev
      - libatlas-base-dev
      - lcov
      - swig3.0
install:
  - pyenv shell 2.7 3.6
  - mkdir -p ~/bin/ && ln -s /usr/bin/swig3.0 ~/bin/swig && export PATH=~/bin/:$PATH
  - pip3 install --upgrade setuptools wheel pkgconfig
  - pip3 install --upgrade -r ./.travis_pip_reqs.txt
  - pip3 install .

# run tests

script:  
  - python3 -m pytest ./test
  - python3 -m flake8 --ignore=F401 --exclude=doc,build

#after_success:
#  - python3 ./test/code_coverage.py
#  - bash <(curl -s https://codecov.io/bash) -f coverage_py.xml -X fix

# cache dependencies

cache: pip

